#ddev-generated
services:
  elasticsearch:
    image: ${ELASTICSEARCH_DOCKER_IMAGE:-elasticsearch:7.17.27}
    volumes:
      - ./elasticsearch/config/elasticsearch7.yml:/usr/share/elasticsearch/config/elasticsearch.yml
